---
title: "Biostat 620 - Final Project EDA"
author: "Spencer Haupert"
date: "4/22/2021"
output: pdf_document
---

```{r, warnings=FALSE}
#Packages
library(tidyverse) #processing
library(circular) #angular pickup time
library(lubridate) #handle date data easily
library(MASS) #
library(mice) #imputation
library(gridExtra) #arrange plots
library(webshot) #arrange plots
library(grid) #arrange plots
library(gtsummary) #nice tables
library(psych) #summary stats

```

```{r}
### Reading in the data ###
base.df = read.csv(file = "crossover_full_deid.csv", header=TRUE)

cov.df = read.csv(file = "baseline_full_deid.csv", header=TRUE)
```

```{r}
### Processing ###

#Fix mistake in DOW
base.df$Day = ifelse(base.df$Day == "Fi", "Fr", base.df$Day)

#Column for day of observation and score
base.df = base.df %>%
  mutate(index = rep(1:25,24),
         score = 0.4*Tot.Scr.Time + 0.6*Pickups)

#Column for treatment sequence
seq.df = as.data.frame(matrix(base.df$Treatment,ncol=24,nrow=25), stringsAsFactors = FALSE)
seq.vec = rep("AA", 24)

for(i in 1:24) {
  seq.vec[i] = paste(seq.df[15,i],seq.df[22,i],sep="")
}

base.df$Sequence = rep(seq.vec, each=25)

#Column for team
#?????

#Add covariate data to main df
base.df = merge(base.df,cov.df, by="pseudo_id")


#Process Interval Data
base.df$X1st.Pickup = as.POSIXct(base.df$X1st.Pickup, format="%H:%M", tz="UTC")

base.df = base.df %>%
    mutate(X1st.Pickup = ifelse(pseudo_id == 1, X1st.Pickup + minutes(30), X1st.Pickup))

base.df$X1st.Pickup = as.POSIXct(base.df$X1st.Pickup, origin = '1970-01-01', tz="UTC")

base.df = base.df %>%
    mutate(X1st.Pickup = ifelse(pseudo_id == 9, X1st.Pickup + hours(1), X1st.Pickup))

base.df$X1st.Pickup = as.POSIXct(base.df$X1st.Pickup, origin = '1970-01-01', tz="UTC")

#Column for angular pickup time
base.df = base.df %>%
  mutate(Pickup.1st.angular = (hour(X1st.Pickup)*60+minute(X1st.Pickup))/(24*60)*360)

# Impute NAs in first pickups
imp = mice(subset(base.df, select = -X1st.Pickup))
comp.pickup = complete(imp)

base.df$Pickup.1st.angular = comp.pickup$Pickup.1st.angular

#Verify data is clean and makes sense
levels(as.factor(base.df$Day))

levels(as.factor(base.df$Treatment))

levels(as.factor(base.df$Period))

levels(as.factor(base.df$Sequence))

```


```{r}
#### Descriptive stats ####
#Desc stats
base.df %>% 
  select(age, sex, Tot.Scr.Time, Tot.Soc.Time, Pickups, score, Pickup.1st.angular) %>%
  mutate(sex = ifelse(sex==1, "Male", "Female")) %>%
  tbl_summary(missing_text="(Missing)",
              label = list(Tot.Scr.Time ~ "Total Screen Time",
                           Tot.Soc.Time ~ "Total Social Time",
                           score ~ "Total Usage",
                           Pickup.1st.angular ~ "1st Pickup (Angular)",
                           age ~ "Age",
                           sex ~ "Sex"),
              type = list(age ~ 'continuous'),
              statistic = list(age ~ "{median} ({p25}, {p75})")) %>%
  modify_header(label ~ "**Variable**") %>%
  as_gt() %>%
  gt::tab_header(title = "Table 1. Descriptive Statistics")

#by Treatment
base.df %>% 
  select(Treatment,Tot.Scr.Time, Tot.Soc.Time, Pickups, score, Pickup.1st.angular) %>%
  tbl_summary(by = Treatment, missing_text="(Missing)",
              label = list(Tot.Scr.Time ~ "Total Screen Time",
                           Tot.Soc.Time ~ "Total Social Time",
                           score ~ "Total Usage",
                           Pickup.1st.angular ~ "1st Pickup (Angular)")) %>%
  add_p() %>%
  add_overall() %>%
  modify_spanning_header(c("stat_1", "stat_2", "stat_3", "stat_4") ~ "**Treatment**") %>%
  modify_header(label ~ "**Variable**") %>%
  as_gt() %>%
  gt::tab_header(title = "Table 2. Descriptive Statistics by Treatment")

#by Sequence
base.df %>% 
  select(age, sex, Sequence,Tot.Scr.Time, Tot.Soc.Time, Pickups, score, Pickup.1st.angular) %>%
  tbl_summary(by = Sequence, missing_text="(Missing)",
              label = list(Tot.Scr.Time ~ "Total Screen Time",
                           Tot.Soc.Time ~ "Total Social Time",
                           score ~ "Total Usage",
                           Pickup.1st.angular ~ "1st Pickup (Angular)",
                           age ~ "Age",
                           sex ~ "Male"),
              type = list(age ~ 'continuous'),
              statistic = list(age ~ "{median} ({p25}, {p75})")) %>%
  add_p() %>%
  add_overall() %>%
  modify_spanning_header(c("stat_1", "stat_2", "stat_3", "stat_4", "stat_5", "stat_6") ~ "**Sequence**") %>%
  modify_header(label ~ "**Variable**") %>%
  as_gt() %>%
  gt::tab_header(title = "Table 1. Descriptive Statistics by Sequence")

```


```{r}
### Plots ###

#Boxplot of relevant variables by treatment
box.TST = base.df %>%
    ggplot(aes(x = Treatment, y = Tot.Scr.Time))+
    geom_boxplot()+
    labs(y = "Total Screen Time")

box.pickups = base.df %>%
    ggplot(aes(x = Treatment, y = Pickups))+
    geom_boxplot()+
  labs(y = "Pickups")

box.score = base.df %>%
    ggplot(aes(x = Treatment, y = score))+
    geom_boxplot()+
    labs(y = "Total Usage")

require(gridExtra)
grid.arrange(box.TST, box.pickups, box.score, ncol = 3, top=textGrob("Boxplots of Total Screen Time, Pickups, and Total Usage by Treatment"))
```

```{r fig.height=5, fig.width=10}
#Boxplots by Treatment and Sequence
box.TST2 = base.df %>%
    ggplot(aes(x = Treatment, y = Tot.Scr.Time, color = Sequence))+
    geom_boxplot()+
    labs(y = "Total Screen Time")

box.pickups2 = base.df %>%
    ggplot(aes(x = Treatment, y = Pickups, color = Sequence))+
    geom_boxplot()+
    labs(y = "Pickups")

box.score2 = base.df %>%
    ggplot(aes(x = Treatment, y = score, color = Sequence))+
    geom_boxplot()+
    labs(y = "Total Usage") +
    ggtitle("Figure 2. Boxplots of Total Usage by Treatment and Sequence")


box.score3 = base.df %>%
    ggplot(aes(x = Treatment, y = score, color = as.factor(sex)))+
    geom_boxplot()+
    labs(y = "Total Usage") +
    ggtitle("Figure 3. Boxplots of Total Usage by Treatment and Sex")+
    scale_color_discrete(name = "Sex")

box.score2

box.score3




```

```{r}
#total usage over time by team
rect1 = data.frame(xmin=15,xmax=18, ymin=-Inf, ymax=Inf)
rect2 = data.frame(xmin=22,xmax=25, ymin=-Inf, ymax=Inf)

base.df %>%
  ggplot(aes(x = index, y = score, color = as.factor(Sequence), fill = as.factor(pseudo_id)))+
  geom_line()+
  geom_rect(data=rect1, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),
            fill = "blue",
            alpha=0.25, 
            inherit.aes = FALSE)+
  geom_rect(data=rect2, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),
            fill = "red",
            alpha=0.25, 
            inherit.aes = FALSE)+
  geom_label(label = "Treatment 1",
             x=16.5,
             y=400,
             label.padding = unit(0.15,"lines"),
             label.size = 0.25,
             color = "blue",
             inherit.aes=FALSE,
             size=3)+
  geom_label(label = "Treatment 2",
             x=23.5,
             y=400,
             label.padding = unit(0.15,"lines"),
             label.size = 0.25,
             color = "red",
             inherit.aes=FALSE,
             size=3)+
  ggtitle("Figure 3. Total Usage Over Time by Sequence Group")+
  labs(x = "Day", y="Total Usage")+
  scale_color_discrete(name = "Sequence")


```


```{r}
#Corrplot
corr.df = base.df %>%
  select(Treatment, Sequence, age, sex,Tot.Scr.Time,Tot.Soc.Time,Pickups,score,Pickup.1st.angular) %>%
  na.omit

corr.df$Sequence = as.factor(corr.df$Sequence)
corr.df$Treatment = as.factor(corr.df$Treatment)

pairs.panels(corr.df, method = "pearson",
             hist.col = "#00AFBB",
             density = TRUE,
             ellipses = FALSE,
             gap= 0,
             pch = ".")
```


```{r}
#ACF - overall
acf.df = base.df %>%
  group_by(index) %>%
  summarise(med.score = median(score))

acf(acf.df$med.score)
```
```{r}
#Additional Scatterplots

#scatter plot
  ggplot(data=base.df, aes(x = .40 * Tot.Scr.Time, y = .6 * Pickups, color = Sequence)) + 
  geom_point ()+
  ggtitle("Scatterplot of Weighted Total Screen Time vs Weighted Pickups by Sequence")
  
  
#scatter plot facetted by sex
  ggplot(data=base.df, aes(x = .40 * Tot.Scr.Time, y = .6 * Pickups, color = Sequence)) + 
    geom_point () +
    facet_grid(~sex)+
    ggtitle("Scatterplots of Weighted Total Screen Time vs Weighted Pickups by Sequence and Sex")

```


